export const sampleProducts = [
  // Tazas
  {
    id: "taza-ceramica-11oz",
    name: "Taza de Cerámica 11 oz",
    category: "tazas",
    description: "Taza de cerámica blanca de 11 oz, ideal para personalización con logo empresarial",
    price: 45.0,
    image: "/white-ceramic-mug-11oz.jpg",
    stock: 500,
    minQuantity: 50,
    multipleOf: 25,
    features: ["Cerámica de alta calidad", "Apta para microondas", "Personalización incluida"],
    colors: ["Blanco", "Negro", "Azul", "Rojo"],
    printingMethods: ["Sublimación", "Serigrafía"],
  },
  {
    id: "taza-magica-negra",
    name: "Taza Mágica Negra 11 oz",
    category: "tazas",
    description: "Taza mágica que cambia de color con líquidos calientes, acabado negro mate",
    price: 85.0,
    image: "/black-magic-mug-color-changing.jpg",
    stock: 300,
    minQuantity: 50,
    multipleOf: 25,
    features: ["Cambia de color con calor", "Efecto sorpresa", "Personalización full color"],
    colors: ["Negro"],
    printingMethods: ["Sublimación"],
  },

  // Termos
  {
    id: "termo-acero-500ml",
    name: "Termo de Acero Inoxidable 500ml",
    category: "termos",
    description: "Termo térmico de acero inoxidable con doble pared, mantiene temperatura por 12 horas",
    price: 185.0,
    image: "/stainless-steel-thermal-bottle-500ml.jpg",
    stock: 200,
    minQuantity: 25,
    multipleOf: 25,
    features: ["Doble pared", "Mantiene frío/calor 12h", "Libre de BPA", "Tapa hermética"],
    colors: ["Plata", "Negro", "Azul", "Rojo"],
    printingMethods: ["Grabado láser", "Serigrafía"],
  },
  {
    id: "termo-deportivo-750ml",
    name: "Termo Deportivo 750ml",
    category: "termos",
    description: "Termo deportivo con boquilla de seguridad y asa de transporte",
    price: 165.0,
    image: "/sports-water-bottle-750ml.jpg",
    stock: 350,
    minQuantity: 50,
    multipleOf: 25,
    features: ["Boquilla anti-derrame", "Asa de transporte", "Libre de BPA"],
    colors: ["Negro", "Azul", "Verde", "Rojo"],
    printingMethods: ["Serigrafía", "Tampografía"],
  },

  // Plumas
  {
    id: "pluma-metalica-ejecutiva",
    name: "Pluma Metálica Ejecutiva",
    category: "plumas",
    description: "Pluma de metal con acabado premium, ideal para regalos corporativos",
    price: 35.0,
    image: "/executive-metal-pen.jpg",
    stock: 1000,
    minQuantity: 100,
    multipleOf: 50,
    features: ["Acabado metálico", "Tinta azul", "Estuche incluido", "Grabado láser"],
    colors: ["Plata", "Dorado", "Negro"],
    printingMethods: ["Grabado láser"],
  },
  {
    id: "pluma-plastico-touch",
    name: "Pluma Plástica con Touch",
    category: "plumas",
    description: "Pluma de plástico con punta touch para dispositivos móviles",
    price: 12.0,
    image: "/plastic-stylus-pen-touch.jpg",
    stock: 2000,
    minQuantity: 250,
    multipleOf: 100,
    features: ["Punta touch", "Clip metálico", "Tinta negra"],
    colors: ["Azul", "Rojo", "Verde", "Negro", "Blanco"],
    printingMethods: ["Serigrafía", "Tampografía"],
  },

  // Mochilas
  {
    id: "mochila-ejecutiva-laptop",
    name: "Mochila Ejecutiva para Laptop",
    category: "mochilas",
    description: "Mochila ejecutiva con compartimento acolchado para laptop hasta 15.6 pulgadas",
    price: 385.0,
    image: "/executive-laptop-backpack.jpg",
    stock: 150,
    minQuantity: 25,
    multipleOf: 25,
    features: ['Compartimento laptop 15.6"', "Puerto USB", "Resistente al agua", "Múltiples bolsillos"],
    colors: ["Negro", "Gris", "Azul marino"],
    printingMethods: ["Bordado", "Serigrafía"],
  },
  {
    id: "mochila-deportiva",
    name: "Mochila Deportiva",
    category: "mochilas",
    description: "Mochila deportiva ligera con compartimento para zapatos",
    price: 245.0,
    image: "/sports-gym-backpack.jpg",
    stock: 200,
    minQuantity: 50,
    multipleOf: 25,
    features: ["Compartimento para zapatos", "Material resistente", "Correas ajustables"],
    colors: ["Negro", "Azul", "Rojo", "Verde"],
    printingMethods: ["Serigrafía", "Bordado"],
  },

  // Gorras
  {
    id: "gorra-trucker",
    name: "Gorra Trucker",
    category: "gorras",
    description: "Gorra estilo trucker con malla trasera y visera curva",
    price: 75.0,
    image: "/trucker-cap-mesh-back.jpg",
    stock: 500,
    minQuantity: 50,
    multipleOf: 25,
    features: ["Malla trasera", "Ajuste snapback", "Visera curva"],
    colors: ["Negro/Blanco", "Azul/Blanco", "Rojo/Blanco"],
    printingMethods: ["Bordado", "Serigrafía"],
  },
  {
    id: "gorra-premium-bordada",
    name: "Gorra Premium Bordada",
    category: "gorras",
    description: "Gorra de algodón premium con bordado 3D",
    price: 95.0,
    image: "/premium-embroidered-cap.jpg",
    stock: 400,
    minQuantity: 50,
    multipleOf: 25,
    features: ["100% algodón", "Bordado 3D", "Ajuste metálico"],
    colors: ["Negro", "Azul marino", "Gris", "Blanco"],
    printingMethods: ["Bordado"],
  },

  // USB
  {
    id: "usb-metalico-16gb",
    name: "USB Metálico 16GB",
    category: "usb",
    description: "Memoria USB metálica de 16GB con argolla para llavero",
    price: 95.0,
    image: "/metal-usb-drive-16gb.jpg",
    stock: 800,
    minQuantity: 100,
    multipleOf: 50,
    features: ["16GB capacidad", "USB 2.0", "Carcasa metálica", "Argolla incluida"],
    colors: ["Plata", "Negro", "Dorado"],
    printingMethods: ["Grabado láser", "Impresión UV"],
  },
  {
    id: "usb-giratorio-32gb",
    name: "USB Giratorio 32GB",
    category: "usb",
    description: "Memoria USB giratoria de 32GB con protección de conector",
    price: 145.0,
    image: "/swivel-usb-drive-32gb.jpg",
    stock: 600,
    minQuantity: 100,
    multipleOf: 50,
    features: ["32GB capacidad", "USB 3.0", "Diseño giratorio", "Alta velocidad"],
    colors: ["Negro", "Azul", "Rojo"],
    printingMethods: ["Serigrafía", "Impresión UV"],
  },

  // Playeras
  {
    id: "playera-cuello-redondo",
    name: "Playera Cuello Redondo",
    category: "playeras",
    description: "Playera de algodón 100% con cuello redondo, ideal para uniformes",
    price: 85.0,
    image: "/round-neck-cotton-tshirt.jpg",
    stock: 1000,
    minQuantity: 50,
    multipleOf: 25,
    features: ["100% algodón", "Cuello reforzado", "Tallas S-XXL"],
    colors: ["Blanco", "Negro", "Azul marino", "Gris", "Rojo"],
    printingMethods: ["Serigrafía", "Vinil textil", "Sublimación"],
  },
  {
    id: "playera-polo",
    name: "Playera Tipo Polo",
    category: "playeras",
    description: "Playera tipo polo de piqué con botones, perfecta para uniformes ejecutivos",
    price: 135.0,
    image: "/polo-shirt-pique.jpg",
    stock: 600,
    minQuantity: 50,
    multipleOf: 25,
    features: ["Tela piqué", "Cuello con botones", "Corte ejecutivo"],
    colors: ["Blanco", "Negro", "Azul marino", "Gris"],
    printingMethods: ["Bordado", "Serigrafía"],
  },

  // Bolsas
  {
    id: "bolsa-ecologica-tela",
    name: "Bolsa Ecológica de Tela",
    category: "bolsas",
    description: "Bolsa reutilizable de tela de algodón, amigable con el medio ambiente",
    price: 35.0,
    image: "/eco-friendly-cotton-tote-bag.jpg",
    stock: 1500,
    minQuantity: 100,
    multipleOf: 50,
    features: ["100% algodón", "Reutilizable", "Asas reforzadas", "Ecológica"],
    colors: ["Natural", "Negro", "Azul", "Rojo"],
    printingMethods: ["Serigrafía", "Sublimación"],
  },
  {
    id: "bolsa-non-woven",
    name: "Bolsa Non-Woven",
    category: "bolsas",
    description: "Bolsa de tela no tejida, resistente y económica",
    price: 22.0,
    image: "/placeholder.svg?height=400&width=400",
    stock: 2000,
    minQuantity: 250,
    multipleOf: 100,
    features: ["Material resistente", "Económica", "Reutilizable"],
    colors: ["Azul", "Rojo", "Verde", "Negro", "Blanco"],
    printingMethods: ["Serigrafía"],
  },

  // Tecnología
  {
    id: "power-bank-5000mah",
    name: "Power Bank 5000mAh",
    category: "tecnología",
    description: "Batería portátil de 5000mAh con puerto USB, ideal para promocionales",
    price: 185.0,
    image: "/placeholder.svg?height=400&width=400",
    stock: 300,
    minQuantity: 50,
    multipleOf: 25,
    features: ["5000mAh capacidad", "Puerto USB", "Indicador LED", "Cable incluido"],
    colors: ["Negro", "Blanco", "Azul"],
    printingMethods: ["Serigrafía", "Impresión UV"],
  },
  {
    id: "audifonos-bluetooth",
    name: "Audífonos Bluetooth",
    category: "tecnología",
    description: "Audífonos inalámbricos Bluetooth con estuche de carga",
    price: 285.0,
    image: "/placeholder.svg?height=400&width=400",
    stock: 200,
    minQuantity: 25,
    multipleOf: 25,
    features: ["Bluetooth 5.0", "Estuche de carga", "Micrófono integrado", "6h autonomía"],
    colors: ["Negro", "Blanco"],
    printingMethods: ["Impresión UV", "Grabado láser"],
  },
]
